### ISSUE TITLE
Cluster metrics required for dashboards seem to be missing

### ISSUE THREAD

**Issue by tom-mayer** [CrunchyData/pgmonitor#274]
Hey,

we deployed a crunchydata cluster inside our kubernetes with kustomize and pgOperator. The cluster works fine and we enabled metrics. The instance-pods now have the `postgres-operator.crunchydata.com/crunchy-postgres-exporter=true` label and an export sidecar container.
We want to integrate the monitoring in our own monitoring stack (grafana/prometheus) and not use a separate pgmonitor stack for this. We are scraping the instance containers for metrics and all the `ccp_*` metrics seem to be there.  I wanted to port the dashboards from `pgmonitor/grafana/common` to our grafana and imported the json, changing the datasource to our prometheus source. The only metric that seems to be missing is `up{exp_type='pg'}` which is used in the variables declaration for `pgcluster` in `label_values(up{exp_type='pg'}, cluster_name)`. If I remove that temporarily and also remove references to `pgcluster` in the diagrams everything works well. 
So my question is where do I get the `up` metric from? Which pod exposes this, there didn't seem to be any other exporter sidecars than the ones on the pg-instance pods.

**Comment by keithf4** [comment]
So the common dashboards are for a standard, non-container installation and are assuming you've followed the installation instructions here for pgMonitor. We actually have different dashboards for the containers and are what the postgres operator uses for the containers it sets up for you I believe. 

https://github.com/CrunchyData/pgmonitor/tree/main/grafana/containers

Also, the method to query which nodes exist in the cluster may depend on your prometheus configuration. We have an example prometheus configuration is also used in the prometheus container that the postgres operator provides

https://github.com/CrunchyData/pgmonitor/blob/main/prometheus/containers/crunchy-prometheus.yml.containers

It looks like the container PG Overview dashboard is using the `pg_cluster` metric to determine the nodes to display vs the `up{}` metric. And you can see in the above prometheus config file where that metric is gathered using prometheus.

If you need further assistance with this, I may recommend asking in the operator repository since this is more container related than directly related to pgMonitor itself. Feel free to link back to this issue for reference, though. - https://github.com/CrunchyData/postgres-operator

**Comment by keithf4** [comment]
Also for clarification, the `up{}` metric is not part of the exporter itself. It's a metric that prometheus itself adds to targets to indicate whether they are up or not. They may not be added to kubernetes targets which is why it may not be showing up.
