### ISSUE TITLE
Prometheus Rule for No Patroni Leader in HA Cluster

### ISSUE THREAD

**Issue by cbrianpace** [CrunchyData/pgmonitor#334]
Add a standard alert rule to trigger if there is no active Leader within a Postgres HA Cluster (PGO and VM).  Here is an example:

  - alert: NoPrimary
    expr: max by (cluster_name) (ccp_is_in_recovery_status) < 2
    #expr:  max(ccp_is_in_recovery_status{cluster_name=~"hippo"}) < 2
    for: 30s
    labels:
      service: postgresql
      severity: critical
      severity_num: 300
    annotations:
      summary: 'cluster {{ $labels.cluster_name }} does not have a primary instance'

**Comment by keithf4** [comment]
Great idea! Thanks!

**Comment by keithf4** [comment]
Just FYI, I don't think this alert is going to be able to be enabled by default. The `cluster_name` label needs to be provided since, without it, it would look at all PG hosts being monitored and find that max. 

So this will have to be a commented out rule with some notes on how to use it. Unless you can see another way?
