### ISSUE TITLE
Make cache-hit (and potentially other dials) act like dials

### ISSUE THREAD

**Issue by gricey432** [CrunchyData/pgmonitor#350]
**Describe the enhancement you are proposing:**

The cache hit dial (and possibly the others) seem to be calculated on the whole lifetime of the pg stat table. This is misleading when presented as a dial where we'd expect to see instantaneous values. This can hide problems (like a sudden dip in cache hit having almost no impact when the server has been running for months).

The exporter is selecting counters from `pg_stat_database` which grow constantly. So when querying them out we should use `rate` to see the change over time.

This shows the current query being used to calculate the dial:

![image](https://github.com/CrunchyData/pgmonitor/assets/1611345/72b13cdc-ef61-4fec-bcb4-c022b3bd67ae)

This shows my proposed query:

![image](https://github.com/CrunchyData/pgmonitor/assets/1611345/0f7cf538-f60b-488a-bf6f-bd7dffc557bb)

```
sum(rate(ccp_stat_database_blks_hit{pg_cluster="postgres-operator:mycluster",pod=~".*"}[1m]))*100/(sum(rate(ccp_stat_database_blks_hit{pg_cluster="postgres-operator:mycluster",pod=~".*"}[1m]))+sum(rate(ccp_stat_database_blks_read{pg_cluster="postgres-operator:mycluster",pod=~".*"}[1m])))
```

You can see how the intense smoothing of the "instant" value is making it nearly useless.

**Comment by keithf4** [comment]
Good catch. The other dials aren't using cumulative stats that I can see, so I think they're fine. And we had been using `irate` in most other graphs that use cumulative stats, but for some reason the cache hit one had been missed. Thanks!

**Comment by keithf4** [comment]
So I'm going back and looking over this again. When I put the formula you proposed into the dial, it shows near zero the whole time. If I'm not mistaken, I think the intention of this dial is not to show the near-instantaneous cache hit rate over the last minute, but the overall cache hit rate since the database has been running. You can see even in the graph of the original formula you shared, it started around 82%, went down, then went back up again as the cache warmed up. I'd imagine if you restarted the database it would show a dip again regain again. 

So as the formula is now, even though it's doing an overall cumulative sum, if the read rate generally started getting higher than the hit rate over time, the cache ratio would change and go down. 

So, while in a line graph it would make sense to show the rate of cache change over time, only showing those rate values in the dial could be a bit misleading because it's only that cache hit rate for that smaller period of time. So maybe propose adding a new graph panel with that?

Hopefully that makes sense. Or if I'm missing something, happy to discuss further.

**Comment by keithf4** [comment]
And actually going back and re-reading what you said, you are looking for instantaneous in the dial when that's not what I think we originally intended. Maybe renaming the dial to "lifetime cache hit"?

**Comment by keithf4** [comment]
Sorry, we do have a graph for cache hit ratio. And I think your formula would fit better there

**Comment by keithf4** [comment]
I have a PR up with an updated dashboard if you wouldn't mind giving it a look. Note the new minimum version of Grafana is now 9.2 and that is what it was generated with.

https://github.com/CrunchyData/pgmonitor/pull/354

**Comment by gricey432** [comment]
> Sorry, we do have a graph for cache hit ratio. And I think your formula would fit better there

Interesting, I don't have that graph. I'm using PGO and have set up my pgmonitor using the manifests provided through CD Access. Broadly I'm unsure on what I should be doing there since there seems to be a big gap between pgmonitor and pgo's copy of pgmonitor

I'm still of the opinion the dial should be an instant or recent-average value. When someone reports "my postgres is slow" the dials are the first place I'm going for an at-a-glance health report. I can't think of any work where lifetime cache hit ratio would be helpful. The same way "Lifetime average Active Connections" wouldn't be helpful.

Thanks for the PR, if you've got any guidance on how pgmonitor links to / is updated into PGO that'd be a big help (or I can ask support).

**Comment by keithf4** [comment]
The containers have their own set of dashboards because the underlying metric collection is done quite differently, so the label set for filling the dropdowns is different

https://github.com/CrunchyData/pgmonitor/tree/development/grafana/containers

The container team here helps to maintain those, so after this one gets merged into the standalone set of dashboards, we can see about getting those updated. Or we're always happy to accept a PR as well.
